package nl.amis.model4.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import nl.amis.model4.types.GetDeptFindByPK;
import nl.amis.model4.types.GetDeptFindByPKResponse;
import nl.amis.model4.types.GetEmpFindByID;
import nl.amis.model4.types.GetEmpFindByIDResponse;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(targetNamespace="http://nl.amis.hr.service", 
            name="ScottService4")
@XmlSeeAlso(
  { nl.amis.model4.types.ObjectFactory.class })
public interface ScottService4
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://nl.amis.hr.service/ScottService4/getDepartmentRequest",
          output="http://nl.amis.hr.service/ScottService4/getDepartmentResponse")
  @WebResult(targetNamespace="http://nl.amis.hr.entities", 
             partName="parameters",
             name="getDepartmentResponse")
  public GetDeptFindByPKResponse getDepartment(@WebParam(targetNamespace="http://nl.amis.hr.entities",
                                                         partName="parameters", 
                                                         name="getDepartmentRequest")
                                               GetDeptFindByPK parameters);
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://nl.amis.hr.service/ScottService4/getEmployeeRequest",
          output="http://nl.amis.hr.service/ScottService4/getEmployeeResponse")
  @WebResult(targetNamespace="http://nl.amis.hr.entities", 
             partName="parameters",
             name="getEmployeeResponse")
  public GetEmpFindByIDResponse getEmployee(@WebParam(targetNamespace="http://nl.amis.hr.entities",
                                                      partName="parameters", 
                                                      name="getEmployeeRequest")
                                            GetEmpFindByID parameters);
}
