package nl.whitehors.ws.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;

import nl.whitehors.ws.client.types.ObjectFactory;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL",
  targetNamespace="http://ws.whitehorses.nl/", name="HelloImpl")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface HelloImpl
{
  @WebMethod
  @Action(input="http://ws.whitehorses.nl/HelloImpl/sayHello")
  @RequestWrapper(localName="sayHello", targetNamespace="http://ws.whitehorses.nl/",
    className="nl.whitehors.ws.client.types.SayHello")
  @Oneway
  public void sayHello(@WebParam(targetNamespace="", name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://ws.whitehorses.nl/HelloImpl/callbackMessage")
  @RequestWrapper(localName="callbackMessage", targetNamespace="http://ws.whitehorses.nl/",
    className="nl.whitehors.ws.client.types.CallbackMessage")
  @Oneway
  public void callbackMessage(@WebParam(targetNamespace="", name="arg0")
    String arg0);
}
