package nl.whitehors.ws.client;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL",
  targetNamespace="http://ws.whitehorses.nl/", name="HelloImplService")
public class HelloImplService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("nl.whitehors.ws.client.HelloImplService");
      URL baseUrl = HelloImplService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            HelloImplService.class.getResource("http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7101/TestSOAPS3-service-context-root/HelloImplPort?WSDL",
          e);
    }
  }

  public HelloImplService()
  {
    super(wsdlLocationURL,
          new QName("http://ws.whitehorses.nl/", "HelloImplService"));
  }

  public HelloImplService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="HelloImplPort")
  public HelloImpl getHelloImplPort()
  {
    return (HelloImpl) super.getPort(new QName("http://ws.whitehorses.nl/",
                                               "HelloImplPort"),
                                     HelloImpl.class);
  }

  @WebEndpoint(name="HelloImplPort")
  public HelloImpl getHelloImplPort(WebServiceFeature... features)
  {
    return (HelloImpl) super.getPort(new QName("http://ws.whitehorses.nl/",
                                               "HelloImplPort"),
                                     HelloImpl.class, features);
  }
}
