package nl.whitehorses.clientosb.jms;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Mon Sep 06 20:15:03 CEST 2010  
 */

public interface HelloWorldService extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://saml.ws.whitehorses.nl/}sayHello   */

  public java.lang.String sayHello() throws java.rmi.RemoteException;
    public void sayHelloAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
  
}