package nl.whitehorses.client.jms;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Sun Aug 01 00:33:34 CEST 2010 */

public class HelloWorldJMSService_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements nl.whitehorses.client.jms.HelloWorldJMSService {

  public HelloWorldJMSService_Impl() throws javax.xml.rpc.ServiceException {
    this("nl/whitehorses/client/jms/HelloWorldJMSService_saved_wsdl.wsdl", null);
  }
  
  public HelloWorldJMSService_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public HelloWorldJMSService_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://nl/whitehorses/ws/jms", "HelloWorldJMSService"),
          "nl/whitehorses/client/jms/HelloWorldJMSService_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: HelloWorldJMSPort 
  // Port Type: HelloWorld 
  //***********************************

  nl.whitehorses.client.jms.HelloWorld mvar_HelloWorldJMSPort;

  /**
   * returns HelloWorldJMSPort port in this service 
   */
  public nl.whitehorses.client.jms.HelloWorld getHelloWorldJMSPort() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_HelloWorldJMSPort == null) {
      mvar_HelloWorldJMSPort =
        new nl.whitehorses.client.jms.HelloWorld_Stub(_getPort("HelloWorldJMSPort"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_HelloWorldJMSPort)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_HelloWorldJMSPort;
  }

  /**
   * @deprecated  Use getHelloWorldJMSPort(byte[] username, byte[] password)
   */
  public nl.whitehorses.client.jms.HelloWorld getHelloWorldJMSPort(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getHelloWorldJMSPort();
  }

  public nl.whitehorses.client.jms.HelloWorld getHelloWorldJMSPort(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getHelloWorldJMSPort();
  }
  
  
}